### ISSUE TITLE
batch size and sample size order

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [tensorflow/probability#1021]
Dear all,
I have a 2-dimensional observation which I am going to do the regression model for that. In total I have 2000 samples.
When I am checking the `model.batch_shape` and  `model.event_shape` it seems, based on the shape interpretation, all are OK.

```python
model.batch_shape, model.event_shape
((TensorShape([]), TensorShape([]), TensorShape([]), TensorShape([2])),
 (TensorShape([2000]), TensorShape([]), TensorShape([]), TensorShape([2000])))
```
However, when I am sampling the priors, let's say drawn 6 chains, here is what I get:
```python
d_sample, sigma_br_sample, sigma_ik_sample, model_sample = model.sample(6)
print(d_sample.shape)
print(sigma_br_sample.shape)
print(sigma_ik_sample.shape)
print(model_sample.shape)

(6, 2000)
(6,)
(6,)
(2, 6, 2000)
```
From what I read and I understand, the model shape (likelihood) should be `(n_sample, n_batch, n_events)`. But as you see the `n_batch` and `n_sample` are swapped.

Thanks to all,
```
tensorflow_probability 0.10.0
tensorflow 2.2.0`
```

Here is the full code

```python
import tensorflow as tf
import tensorflow_probability as tfp
import pandas as pd
tfd = tfp.distributions
tfb = tfp.bijectors

A0 = 9.50e+01; B0 = 5.52e-03; C0 = 1.00e+00;   
a0 = tf.math.log(A0); b0 = tf.math.log(B0); c0 = tf.math.log(C0);
A1 = 8.50e+01; B1 = 5.00e-04; C1 = 1.67e-04;
a1 = tf.math.log(A1); b1 = tf.math.log(B1); c1 = tf.math.log(C1);

Root = tfd.JointDistributionCoroutine.Root  # Convenient alias.
def model():
    d_lower  = -30*tf.ones(shape=2000, dtype=tf.dtypes.float32)
    d_upper  = 30*tf.ones(shape=2000, dtype=tf.dtypes.float32)
    d_p      = tfd.Uniform(low=d_lower, high=d_upper)
    d_p      = yield Root(tfd.Independent(d_p, name='d_p', reinterpreted_batch_ndims=1))
    sigma_br = yield Root(tfd.HalfNormal(scale = 0.1, name ='sigma_br'))
    sigma_ik = yield Root(tfd.HalfNormal(scale = 0.1, name ='sigma_ik'))
    brca2_hat  = a0+ tf.math.log(tf.math.exp(b0)+tf.math.exp(c0+d_p))-tf.math.log(1+tf.math.exp(c0+d_p))
    ikbkap_hat = a1+ tf.math.log(tf.math.exp(b1)+tf.math.exp(c1+d_p))-tf.math.log(1+tf.math.exp(c1+d_p))
    y_model = yield tfd.MultivariateNormalDiag(loc=[brca2_hat,ikbkap_hat],
                                               scale_identity_multiplier=[sigma_br, sigma_ik])    
model = tfd.JointDistributionCoroutine(model)

print(model.batch_shape)
print(model.event_shape)

d_sample, sigma_br_sample, sigma_ik_sample, model_sample = model.sample(6)
print(d_sample.shape)
print(sigma_br_sample.shape)
print(sigma_ik_sample.shape)
print(model_sample.shape)
```

**Comment by derifatives** [comment]
- When `model.sample(6)` is called, that 6 is only passed directly to the `Root` distributions. 
- The model generates intermediate variables (`brca2_hat` and `ibkap_hat`) with shape [6, 2000].
- The model then constructs a `MultivariateNormal` diag whose `loc` parameter is `[brca2_hat, ikbkap_hat]`. This is (implicitly) equivalent to a `tf.stack` along the 0'th axis, so `loc` has shape `[2, 6, 2000]`. Similarly, `location_scale_parameter` has shape `[2, 6]`.  The constructed multivariate normal has event shape `2000` and a batch shape of `[2, 6]` rather than the desired `[6, 2]`.
- The obvious fix is to explicitly stack / reshape the subparts of the multivariate normal's location and scale multilpliers (example below). This is a general issue with hierarchical models represented as JointDistributions: the sample shapes of "root" distributions become part of the batch shapes of child distributions. In the non-autobatched JD formulations, this requires careful management.
- There is a separate issue with the model as written: `log_prob(sample())` does not return a scalar. This is because even for a single sample, the multivariate normal has a batch shape of `[2]`. This `[2]` should be moved into the event shape using `tfd.Independent`.

To sum up, a variant of the final `MultivariateNormalDiag` that fixes issues I currently know about is:
```
   y_model = yield tfd.Independent(
        tfd.MultivariateNormalDiag(
            loc=tf.stack([brca2_hat, ikbkap_hat], axis=-2),
            scale_identity_multiplier=tf.stack([sigma_br, sigma_ik], axis=-1)),
        reinterpreted_batch_ndims=1)
```

A better fix IMO would be to use JointDistributionCoroutineAutoBatched, which simplifies things considerably because the user only writes a single sample path. If you do that, the original call to `MultivariateNormalDiag` is fine as written (no need for worrying about stacking axes or `tfd.Independent`), and you can remove all the calls to `Root`. The AutoBatched variations can sometimes be less performant, but if you're not worried about the bleeding edge of performance they're great.
