### ISSUE TITLE
Resuming sampling on an MCMC chain produces different results than running it in one go.

### ISSUE THREAD

**Issue by merplumander** [tensorflow/probability#1193]
Python 3.6.5
tensorflow==2.3.1
tensorflow-probability==0.11.1

I am resuming the computations on an MCMC chain based on the code that @SiegeLordEx  provided in this issue: https://github.com/tensorflow/probability/issues/356 . I had hoped that, when setting random seeds, both running the chain in one go and running it with a break in between would produce equivalent results, but this is not the case. Here's a minimal running example:

```
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

def target_log_prob(x):
    return tfd.Normal(0, 1).log_prob(x)

current_state = 1.0
tf.random.set_seed(0)
kernel = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob, step_size=0.01, num_leapfrog_steps=5
)
kernel = tfp.mcmc.DualAveragingStepSizeAdaptation(
    kernel, num_adaptation_steps=0
)

kernel_results = kernel.bootstrap_results(current_state)
chain_blocks = []
chain, trace, kernel_results = tfp.mcmc.sample_chain(
    num_results=6,
    current_state=current_state,
    previous_kernel_results=kernel_results,
    trace_fn=None,
    return_final_kernel_results=True,
    kernel=kernel,
)

chain_blocks.append(chain)

full_chain = tf.nest.map_structure(
    lambda *parts: tf.concat(parts, axis=0), *chain_blocks
)
full_chain
==> <tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.95324814, 0.65667903, 1.315684  , 2.2830935 , 1.7665763 ,
       1.5946238 ], dtype=float32)>

# Let's run the same chain but with a break in between

current_state = 1.0
tf.random.set_seed(0)
kernel = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob, step_size=0.01, num_leapfrog_steps=5
)
kernel = tfp.mcmc.DualAveragingStepSizeAdaptation(
    kernel, num_adaptation_steps=0
)

kernel_results = kernel.bootstrap_results(current_state)
chain_blocks = []
for i in range(2):
    chain, trace, kernel_results = tfp.mcmc.sample_chain(
        num_results=3,
        current_state=current_state,
        previous_kernel_results=kernel_results,
        trace_fn=None,
        return_final_kernel_results=True,
        kernel=kernel,
    )
    current_state = tf.nest.map_structure(lambda x: x[-1], chain)
    chain_blocks.append(chain)


full_chain = tf.nest.map_structure(
    lambda *parts: tf.concat(parts, axis=0), *chain_blocks
)
full_chain
==> <tf.Tensor: shape=(6,), dtype=float32, numpy=
array([ 0.95324814,  0.65667903,  1.315684  ,  0.73805386,  0.6957903 ,
       -0.23172122], dtype=float32)>
```

So the first three samples are equivalent. Apparently setting a seed with tf.random.set_seed() is enough to get reproducible results. But after resuming, the chains produce different samples.

I have also tried to provide a seed to `tfp.mcmc.HamiltonianMonteCarlo()` but this results in the following error:
`Specifying a seed when running eagerly is not currently supported. To run in Eager mode with a seed, pass the seed to tfp.mcmc.sample_chain.`
But of course, passing a seed to `tfp.mcmc.sample_chain` also doesn't work because I have to set it twice in the second code example with the break in between.

Any help on getting the same samples in the first as in the second case would be greatly appreciated! :)

**Comment by csuter** [comment]
Hi! I started writing a response to -- I think -- your stackoverflow post the other day; sorry for not finishing and posting!

The short answer is, sadly, this is tricky/not possible. We have a standard practice in our library, which is to "salt" incoming seeds at the beginning of functions that do things with PRNGs. This means that it is very hard to pass in the "right" seed to sample_chain to get it to resume where a previous one left off. If we *didn't* salt the seed (or made the salt a configurable and hence optional argument), then you could do this, in principle, by manually 1. calling sample_chain for N results with a given seed, 2. manually "splitting" that seed N times to recover the final internal seed state of the first sample_chain call, 3. invoking sample_chain again with that N-times-split seed. Technically this relies on internal details about how sample_chain is implemented (how it splits seeds), which is not something we'd want to commit to as part of API contract. So it's unlikely that doing this reliably will be supported.

If some of what I said above (about splitting seeds and such) sounds unfamiliar, check out our note on PRNGs [here](https://github.com/tensorflow/probability/blob/master/PRNGS.md). From your example, it appears you're relying on the old, stateful seed functionality which, while still supported, is generally harder to make reproducible than the newer stateless seed functionality. In both cases, however, getting the results you're aiming for here is not currently supported.

To clarify the error message you're seeing -- we used to only take seeds as constructor arguments on HMC and other kernels. We've since revised the API to encourage passing them to sample_chain instead, but the old behavior is still supported (for now). Hence the warnings. These days we recommend you 1. use the sample_chain seed argument, 2a. use stateless seeds (see PRNG doc linked above) and 2b. by virtue of using stateless seeds, forget about tf.set_random_seed (it doesn't always work and sometimes doesn't do what you might think!).

**Comment by merplumander** [comment]
Thanks for the detailed response!
I'll settle for "too tricky". It was not that important to me and I thought it might be as easy as changing a seed in the previous kernel results or something like that.
The note on PRNGs was quite enlightening, and I'll work with the stateless see functionality from now.
