### ISSUE TITLE
Two instances of MultivariateNormalTril with same parameters can return different prob and log_prob for same sample

### ISSUE THREAD

**Issue by aapo-kossi** [tensorflow/probability#1281]
My network depends on being able to retroactively calculate the log_prob of a sample, but I am getting wildly incorrect results when calculating the value from a new distribution instance instead of the one from which the sample is taken.
Simplified code snippet to reproduce the issue, where final_mu.shape = (16, 10) and L is a lower triangular with diag_part > 0, shaped (16, 10, 10), both output from a neural network:

```
dist = MultivariateNormalTriL(loc = final_mu, scale_tril = L)
raw_action = dist.sample()

dist2 = MultivariateNormalTriL(loc = final_mu, scale_tril = L)

assert tf.reduce_all(dist2.mean() == dist.mean()) and \
       tf.reduce_all(dist2.covariance() == dist.covariance())
assert tf.reduce_all(dist.log_prob(raw_action) == dist2.log_prob(raw_action))
assert tf.reduce_all(dist.prob(raw_action) == dist2.prob(raw_action))
```
yielding AssertionError on
`assert tf.reduce_all(dist.log_prob(raw_action) == dist2.log_prob(raw_action))`

**Comment by davmre** [comment]
It's possible that you're running into an numerical issue, and that TFP's bijector caching is hiding this issue when you evaluate with the same distribution instance. 

As context, multivariate normal distributions are implemented in TFP as `TransformedDistribution(distribution=Normal, bijector=Shift(final_mu)(ScaleMatvecTriL(L)))`, and bijectors in TFP cache their inputs and outputs. Calling `dist2.log_prob(raw_action)` will necessarily invoke the bijector `inverse`, while `dist.log_prob(raw_action)` is a cache hit and can skip the explicit inverse because it will just return the original value it sampled from the underlying `Normal`. This saves computation and can be numerically beneficial, but has the effect of concealing any numerical issues with the transformation.

I'm guessing that your scale matrix `L` is poorly conditioned, so that if you run

```
z = tfd.Normal(0., 1.).sample(L.shape[-1])
x = tf.linalg.matvec(L, z)
z_ = tf.linalg.triangular_solve(L, z)
```

you'll see `z != z_`. If so, the usual solutions are to either try to create a better-conditioned matrix (often by doing something like `scale_tril = L + eps * tf.eye(L.shape[-1])` for some `eps`), or try running your code with `float64` values.

**Comment by aapo-kossi** [comment]
You are absolutely correct, the bijector caching was hiding problems with `L`.
I was already adding an epsilon to the diagonal, but it seems that my network starts converging to such `L` that result in this issue even with large epsilon. 
That said, the issue I posted about is solved, thank you.
