### ISSUE TITLE
Add Edward2 program transformation to unconstrain all random variables

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#131]
Given an Edward program with continuous-only random variables, consider a function `make_unconstrained` which returns a new program unconstraining the support of all its random variables. This lets us apply HMC over constrained latents by going from `model -> make_unconstrained -> make_log_joint_fn`. Clear win for the program_transformations submodule!

```
def make_unconstrained(model):
  def interceptor(rv_constructor, *rv_args, **rv_kwargs):
    # TODO(trandustin): get rv_constructors distribution_constructor
    dist_constructor = None
    dist = dist_constructor(*rv_args, **rv_kwargs)
    # TODO(trandustin): get support of distribution
    rv_unconstrained = ed.TransformedDistribution(dist,
        bijector=)
    return rv_unconstrained

  @functools.wraps(model)
  def unconstrained_program(*args, **kwargs):
    with interception(interceptor):
      return model(*args, **kwargs)

  return unconstrained_program
```

**Comment by davmre** [comment]
`# TODO(trandustin): get rv_constructors distribution_constructor`

Can't you just use the `rv_constructor` directly? As long as you don't rewrap it as `interceptable`, just calling the constructor won't appear in higher-level traces / log joints. Using the RV constructor also saves needing to strip out RV-specific arguments like `value` and `sample_shape`. (though in general those still need to be handled appropriately by the TransformedDistribution).

FWIW I also think you want to return the bijector-transformed value `return bijector.forward(rv_unconstrained)` so that downstream usage sees values in the original constrained space. (e.g., if the RV is used downstream as a variance parameter, we need to return a positive value).

Anyway, agreed this would be super useful! (in addition to HMC, it also automatically gives you ADVI by putting a mean-field normal posterior on the unconstrained model). I think the main blocker is figuring out how to annotate supports for distributions.

**Comment by dustinvtran** [comment]
> Can't you just use the rv_constructor directly? 

You are correct. This is a copy-pasta'd snippet from an old, internal issue.

I agree with both your approach and the bijector suggestion.

**Comment by srvasude** [comment]
Closing this, as Edward2's repository is now located here: https://github.com/google/edward2
