### ISSUE TITLE
tfp.experimental.mcmc.DiagonalMassMatrixAdaptation

### ISSUE THREAD

**Issue by ctorney** [tensorflow/probability#1348]
Hi,
I've been trying out preconditioned HMC with DiagonalMassMatrixAdaptation in the experimental package. 

It wasn't mixing and I think it's because of this line:
https://github.com/tensorflow/probability/blob/4683836be3701e75f459494bd3de12edb7560a2d/tensorflow_probability/python/experimental/mcmc/preconditioned_hmc.py#L291

Right before this the momentum distribution is set from previous_kernel_results:
https://github.com/tensorflow/probability/blob/4683836be3701e75f459494bd3de12edb7560a2d/tensorflow_probability/python/experimental/mcmc/preconditioned_hmc.py#L260
but because the check is on self.momentum_distribution not momentum_distribution the leapfrog_kinetic_energy_fn isn't set.

I got round this by using
`
kernel = tfp.experimental.mcmc.PreconditionedHamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    num_leapfrog_steps=num_leapfrog_steps,
    step_size=init_step_size,
    momentum_distribution=0,
    store_parameters_in_results=True)`

and then it mixes fine but it seems like it should work if momentum distribution is not specified.
Thanks

**Comment by ColCarroll** [comment]
Hey! Glad you're trying it out. It looks like this got fixed in [this commit](https://github.com/tensorflow/probability/commit/4588e9fa8b83658483bf807e29b6d5a3b9747623), so I'm going to close. 

There is a [pre-release up on PyPI](https://pypi.org/project/tensorflow-probability/0.13.0rc0/) with this included that you can get with
```bash
pip install --upgrade --pre tensorflow-probability tensorflow
```

Alternatively, you can use the nightly builds
```bash
pip install --upgrade tfp-nightly tf-nightly
```

Please keep chiming in if it gives you trouble!
