### ISSUE TITLE
Bug in JointDistribution when using a for loop

### ISSUE THREAD

**Issue by gianlucadetommaso** [tensorflow/probability#1378]
Here is a minimal example:
```
mmm = {"a": tfd.Uniform(0, 1)}
for i in range(2):
    mmm["b" + str(i)] = lambda a: tfd.Normal(loc=tf.zeros([i + 1]), scale=a)
mmm = tfd.JointDistributionNamedAutoBatched(mmm)
mmm.sample()
```
>>> {'a': <tf.Tensor: shape=(), dtype=float32, numpy=0.5270164>,
 'b1': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1.0839868 , -0.50351816], dtype=float32)>,
 'b0': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.56578904, 0.20152093], dtype=float32)>}

`b0` is wrongly defined as it should have shape=(1,). Interestingly, without for loop it works:

```
mmm = {"a": tfd.Uniform(0, 1)}
mmm["b0"] = lambda a: tfd.Normal(loc=tf.zeros([1]), scale=a)
mmm["b1"] = lambda a: tfd.Normal(loc=tf.zeros([2]), scale=a)
mmm = tfd.JointDistributionNamedAutoBatched(mmm)
mmm.sample()
```
>>> {'a': <tf.Tensor: shape=(), dtype=float32, numpy=0.76573205>,
 'b1': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.9614516 , 0.10001361], dtype=float32)>,
 'b0': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8674517], dtype=float32)>}

I suspect something wrong is happening when the lambda function over the same variable `a` is called to define two different variables. I have no idea why this appears only when using a for loop. An analogous problem can be found using `tfd.JointDistributionSequentialAutoBatched` instead.

**Comment by davmre** [comment]
It looks like you're running into the infamous [Python lambda scoping issue](https://louisabraham.github.io/articles/python-lambda-closures.html): lambdas don't capture the values of loop variables, so executing a lambda that was defined inside of a loop will use the *final* value of `i` (always `1` here) instead of the value from when the lambda is defined.

You can check that this actually happens even without using a JointDistribution at all:

```python
for i in range(2):
    mmm["b" + str(i)] = lambda a: tfd.Normal(loc=tf.zeros([i + 1]), scale=a)

b0 = mmm['b0'](1.).sample()
print(b0)  # ==> has shape `[2]`.
```

If you need to define lambdas inside of a loop, one workaround is to explicitly pass `i` as an argument with a default value, which does get captured at definition time:

```python
for i in range(2):
    mmm["b" + str(i)] = lambda a, i=i: tfd.Normal(loc=tf.zeros([i + 1]), scale=a)

b0 = mmm['b0'](1.).sample()
print(b0)  # ==> has shape `[1]`.
```
