### ISSUE TITLE
Force regression coefficients to be positive

### ISSUE THREAD

**Issue by sbohora** [tensorflow/probability#1457]
I am using ``tfp.sts.LinearRegression()`` and wondering how I can force my regression coefficients to be positive.

Any help is much appreciated!!!
Thanks.

```python
tfp.sts.LinearRegression()
```

**Comment by davmre** [comment]
I believe you can just pass a weights prior with positive support, e.g.:

```python
regression_component = tfp.sts.LinearRegression(
  design_matrix,
  weights_prior=tfd.HalfStudentT(df=5, loc=0., scale=1.))
```

This should work because the regression component will use the `weights_prior.experimental_default_event_space_bijector()` to constrain the inferred weights. For example, for a `HalfStudentT` prior this would be the `tfb.Exp()` bijector, which imposes the positivity constraint by representing the weights in log space.

**Comment by sbohora** [comment]
@davmre Thank you.
