### ISSUE TITLE
Chain Forward and Inverse Methods 

### ISSUE THREAD

**Issue by suvoooo** [tensorflow/probability#1470]
Hey just having a slight issue in understanding how the Inverse method works and below is an example where I get inconsistent results

forward method

```
normal = tfd.Normal(loc=0., scale=1.0)
z = normal.sample(1000) 
scale, shift = 4., -0.5

scale_shift = tfb.Chain([tfb.Shift(shift), tfb.Scale(scale)]) # 1st way

scale_transf = tfb.Scale(scale)
shift_transf = tfb.Shift(shift)

scale_and_shift = shift_transf(scale_transf) # 2nd way

x = scale_and_shift.forward(z)

print (tf.norm(x - (scale*z + shift)) ) 
print (tf.norm(x - scale_shift.forward(z)))

>>> tf.Tensor(0.0, shape=(), dtype=float32)
>>> tf.Tensor(0.0, shape=(), dtype=float32)
```
This works great as expected but in the inverse method

```
y = tfb.Chain([tfb.Shift(shift), tfb.Scale(scale)]).inverse(x)
y1 = scale_and_shift.inverse(x)

print (tf.norm(y-z))
print (tf.norm(y1-z))

>>> tf.Tensor(4.0371447e-07, shape=(), dtype=float32)
>>> tf.Tensor(0.0, shape=(), dtype=float32)
```
Why there's a discrepancy in the results? I would assume they would be the same (0.0).

**Comment by davmre** [comment]
This is likely an effect of bijector caching. Doing the actual inverse calculation loses a bit of numerical precision, causing the `4.0371447e-07` discrepancy, but the call `scale_and_shift.inverse(scale_and_shift.forward(z))` avoids this because it hits the cache and returns the original input `z` exactly.

I wouldn't expect any fundamental difference between the two ways of constructing the bijector: `scale_shift` and `scale_and_shift` each have their own input-output cache, so either one should give an exact result when inverting itself (`scale_shift.inverse(scale_shift.forward(z))`) but a slightly-inexact result if you force it to do the numerical calculation (`scale_shift.inverse(scale_shift.forward(tf.identity(z)))`).

**Comment by suvoooo** [comment]
> This is likely an effect of bijector caching: bijectors try to elide inverse calculations by caching their previous inputs. Computing the inverse directly loses a bit of numerical precision, hence the `4.0371447e-07` discrepancy, but the call `scale_and_shift.inverse(scale_and_shift.forward(z))` hits the cache and returns the original input `z` exactly.
> 
> I wouldn't expect any fundamental difference between the two ways of constructing the bijector: `scale_shift` and `scale_and_shift` each have their own input-output cache, so either one should give an exact result when inverting itself (`scale_shift.inverse(scale_shift.forward(z))`) but a slightly-inexact result if you mix-and-match or otherwise force it to do the numerical calculation (e.g., `scale_shift.inverse(scale_shift.forward(tf.identity(z)))`).

Thank you for clearing that up!
