### ISSUE TITLE
"quantile" method is not implemented for distribution

### ISSUE THREAD

**Issue by peng1wang** [tensorflow/probability#1551]
It's a great pity that the "quantile" method is not implemented for distribution in tensorflow probability. Actually this method is very useful.

**Comment by csuter** [comment]
Thanks for the suggestion! Is there a specific distribution you are looking at? Many Distributions do have `quantile` implemented. Cases where it is not implemented are usually because no efficient program for computing them* is known. There may be cases where it's simply been overlooked, however. Please feel free to open Feature Requests (or send Pull Requests!) to implement these where possible.

I'll close this issue as overly broad/not actionable, but please feel free to open further issues as stated above.

* -- per (3) and (4) in [the distributions contract](https://github.com/tensorflow/probability/blob/main/discussion/tfp_distributions_contract.md), such programs must be polynomial time and non-stochastic. Ideally they are "exact" in some limiting sense (ie, up to floating point precision). Sometimes we include explicitly approximate computations, which are known to include some (bounded) error, and we name these specifically `xyz_approx` -- c.f. `LogitNormal.{mean_approx,variance_approx,mean_log_prob_approx}`.
