### ISSUE TITLE
MultivariateNormalDiagPlusLowRank inconsistent with practice

### ISSUE THREAD

**Issue by Bonnevie** [tensorflow/probability#161]
This is maybe more of a feature request, but in short, the fact that the distribution
[MultivariateNormalDiagPlusLowRank](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/MultivariateNormalDiagPlusLowRank) applies the eponymous low-rank assumption to a _scale_ matrix, and not the covariance, is somewhat unorthodox and not really in line with what most practitioners would expect.

In my opinion, it is fairly rare to see people explicitly model a dense scale matrix (although cholesky factors do show up for computational reasons) let alone assume structure. Diagonal-plus-low-rank structure is however very normal, with PPCA having marginal covariance $AA^T+kI$ for instance.

My guess is that this formulation is due to the easy definition as a TransformedDistribution? I think it would be worth it to include a diagonal-plus-low-rank _covariance_ normal distribution since there is a significant computational gain to be had, but unfortunately I do not think there is a way to do this in terms of a transformation. I also think it would be reasonable to emphasize the distinction between low-rank scale and low-rank covariance.

**Comment by csuter** [comment]
Great points, @Bonnevie. One impediment to actually fixing this as you suggest is the lack of a low-rank Cholesky update procedure in TensorFlow. This is something I've been thinking about recently and am working on some proposals to address. No reliable ETA as of yet though. Thanks for raising this issue!

**Comment by Bonnevie** [comment]
@csuter I don't think you really need a low-rank cholesky update, unless I am missing something. By applying [Woodbury's matrix identity](https://en.wikipedia.org/wiki/Woodbury_matrix_identity) you should be able to convert the matrix inverse in the large event space to an inverse in the lower-dimensional latent space. 

I implemented it in Stan at one point, which might be mildly useful if you can decipher the notation (it is for a N(x|mu,B*B^T + diag(sigma)) density):
```
    real multi_normal_lowrank_cholesky_lpdf(vector x, vector mu, vector sigma, matrix B, matrix L) {
        int lowrank = cols(B);  
        vector[lowrank] v = mdivide_left_tri_low(L, B' * ((x-mu) ./ square(sigma)));
        return normal_lpdf(x | mu, sigma) + dot_self(v)/2. - sum(log(diagonal(L)));
    }

    real multi_normal_lowrank_lpdf(vector x, vector mu, vector sigma, matrix B) {
        int lowrank = cols(B);  
        matrix[rows(B),lowrank] Bscaled = diag_pre_multiply(inv(sigma), B);
        matrix[lowrank,lowrank] L = cholesky_decompose(diag_matrix(rep_vector(1,lowrank)) + crossprod(Bscaled));
        return multi_normal_lowrank_cholesky_lpdf(x | mu, sigma, B, L);
    }    
```
From a computational point of view, you can precompute the cholesky factor `L` of the low-dimensional matrix inverse, but it is now a cholesky factor of an auxiliary matrix (B^T*inv(diag(sigma))*B+I), and not the covariance as before.

**Comment by Bonnevie** [comment]
By the way, when the `scale` is defined in [MultivariateNormalDiagPlusLowRank](https://github.com/tensorflow/probability/blob/d8fecd043cde0787d166856cfe1a029ea8325330/tensorflow_probability/python/distributions/mvn_diag_plus_low_rank.py#L243) as
```
          scale = tf.linalg.LinearOperatorLowRankUpdate(
              scale,
              u=scale_perturb_factor,
              diag_update=scale_perturb_diag,
              is_diag_update_positive=scale_perturb_diag is None,
              is_non_singular=True,  # Implied by is_positive_definite=True.
              is_self_adjoint=True,
              is_positive_definite=True,
              is_square=True)
```
the line `is_diag_update_positive=scale_perturb_diag is None` is only true if `scale_perturb_diag` is not supplied. Shouldn't it rather check if the supplied vector is positive? Problematically, if that flag is false the bijector won't use a cholesky decomposition in fear of the scale being non-PSD incurring an unexpected computational cost. Again, this runs a bit counter to most users' expectation; you wouldn't normally anticipate that multiplying by a diagonal has a significant impact on both speed and numerical stability.

**Comment by Bonnevie** [comment]
@csuter I could try to implement this as a PR; are there any guidelines on implementing custom distributions?

**Comment by langmore** [comment]
@Bonnevie You could use the Woodbury identity to compute the inverse (`LinearOperatorLowRankUpdate` already does this).  That would give you the pdf.  For sampling, as you probably know (but it's good to make clear for future readers), you need to factor the operator as `A = S S^T`, and then set the samples `z = S \eps`, where `\eps ~ N(0, I)`.  There currently isn't an efficient way to do this, which is why @csuter is suggesting a low rank Cholesky update.

Now, it may still be desirable to create a distribution parameterized by covariance = `LinearOperatorLowRankUpdate`, and accept sampling will be inefficient.  This would be a custom distribution, as you suggest.  I'll leave it to @csuter to comment on the desirability of this.

Regarding the setting of `is_diag_update_positive=scale_perturb_diag is None`, IIRC, we did not want the user to have to think about keeping `scale_perturb_diag` positive.  Keep in mind that in this case, the computational cost is only incurred in the low-rank space -- the solve/determinant always use the Woodbury/determinant lemmas, and it is only the solve/det of the low rank factor that will be inefficient of `is_diag_update_positive == False`.

**Comment by langmore** [comment]
...to answer directly your question "Shouldn't it rather check if the supplied vector is positive?".  When building this, the expectation was that the vector could change with every graph eval and perhaps be different for different batch members.  This means a check would not be efficient.  If `scale_perturb_diag` is known ahead of time, the user can absorb its square root into `scale_perturb_factor`, then set it to `None`, and the most efficient code path will be used.

**Comment by Bonnevie** [comment]
@langmore if you know that covariance`=SS^T+D` then you can easily sample from it by just doing `z=S\eps_1+D^{1/2}\eps_2` with `\eps_1~N(0,I)`  and `\eps_2 ~ N(0,I)`, you do not need to multiply it by the Cholesky factor specifically, any square-root-like factorization will do. So if you just need sampling, I do not see why it would be inefficient or would require the Cholesky factor in any way, unless you want to use the Cholesky factor in the intermediate step like in my example implementation above.  

The only implementation issue as I see it is that you cannot compute it as a `TransformedDistribution` with an appropriate bijector as `z=S\eps_1+D^{1/2}\eps_2` is not invertible. Or am I misunderstanding something?

Regarding `is_diag_update_positive`, I can see why you wouldn't want to assume positivity in general for the operator, but for covariance matrices I believe it has to be true, unless you are adding a large diagonal term to it afterwards. If you want to leave that door open anyway, I recommend that it is documented how a distribution should be implemented to ensure the Cholesky factorization is used internally so it does not take anyone by surprise.

**Comment by langmore** [comment]
@Bonnevie I agree with your statement, "if you know the covariance is `SS^T + D`..."  I was assuming the starting point where covariance = `C + D`, i.e. we don't the square root.

I agree that the only difficulty is the new distribution would not be a `TransformedDistribution`.

Thanks for the comment about the diagonal term.  Perhaps you could put together a PR with updated documentation?

**Comment by Bonnevie** [comment]
It does not fix the documentation issue, but made a preliminary implementation of the desired distribution class. I tried to base the implementation on existing distributions. Right now it is only accelerating `log_prob`.

**Comment by langmore** [comment]
Thanks @Bonnevie for raising this issue. We have finally put together the requested distribution.  See [`MultivariateNormalDiagPlusLowRankCovariance`](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/mvn_diag_plus_low_rank_covariance.py).  Also of interest is the (hidden) base class [`MultivariateNormalLowRankUpdateLinearOperatorCovariance`](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/mvn_low_rank_update_linear_operator_covariance.py). It's hidden because I'm not sure if the base class should be more general.

Sorry this took so long. Let me know if you have any questions.
