### ISSUE TITLE
`tfd.Binomial.cdf` is continuous wrt the input

### ISSUE THREAD

**Issue by chrism0dwk** [tensorflow/probability#1619]
Hi All,

Small point, but should
```
x = np.linspace(0, 10, 200)
tfd.Binomial(total_count=10, probs=0.7).cdf(x)
```
really be returning a smooth continuous function?  Surely some internal flooring of `x` to its integer value would make more sense, à la R's `pbinom()` function?

C

**Comment by csuter** [comment]
We generally don't restrict these functions to the (technically valid) support of the distribution. Doing so would incur additional op costs (conds/wheres/assertions) which we tend not to include ("be fast by default"). Some distributions include a boolean flag to tell the implementation to be stricter; eg, Poisson has `force_probs_to_zero_outside_support`. This is always done in such a way as to preserve the looser, fast-by-default behavior.

The idea is that, if the user wishes to pay the cost to be stricter, they are free to floor or otherwise constrain/restrict the inputs outside the distribution code. This is similar to having `validate_args=False` and `allow_nan_stats=True` by default.

Hope this makes sense! We'd probably be open to a modification that lets Binomial follow the pattern of Poisson (and others...NegBinom?), as long as the implementation precludes adding ops in the "default fast" case (ie, the flag must be a python boolean, not a tensor, so that the impl can be switched in python-land before any graphs are built).

**Comment by chrism0dwk** [comment]
Yup, understood.  Thanks Chris.
