### ISSUE TITLE
No module named 'tensorflow_probability'

### ISSUE THREAD

**Issue by EliottEccidio** [tensorflow/probability#1732]
Hi,

I want to use your package to do Reinforcement Learning. I did in a jupyter-notebook:

```python
!pip install --upgrade pip
!pip install --upgrade tensorflow tensorflow_probability
```
But when I try to import it :
```python
import tensorflow_probability as tfp
```
I have the error :
```python 
ModuleNotFoundError: No module named 'tensorflow_probability'
# I see it as tensorflow-probability       0.20.1 when I use !pip3 list
```
Can someone help me ?

**Comment by ColCarroll** [comment]
this is probably a jupyter/python packaging issue, but I am guessing that however jupyter is launched, the default `pip` is not the `pip` being run in the kernel. A way to try to fix this would be to use

```
import sys
!{sys.executable} -m pip install --upgrade pip
!{sys.executable} -m pip install --upgrade tensorflow tensorflow_probability
!{sys.executable} -m pip list
```

Using `python -m pip` is generally recommended, since then you know which `python` the `pip` is attached to. Inside a running kernel, `sys.executable` will give you the path to the current python binary.
