### ISSUE TITLE
Distribution Output is Incompatible with Keras Dense Layers

### ISSUE THREAD

**Issue by i418c** [tensorflow/probability#1780]
In the nightly versions of TF and TFP, distributions passed to a Keras dense layer are not subscriptable, causing a crash.
See the gist reproducing this [here](https://gist.github.com/i418c/d58f02b7f89adf4511792e12cd5ea65f#file-tfp-distribution-unsubscriptable-ipynb).

**Comment by csuter** [comment]
Can you make sure the default versions are uninstalled by pip uninstall'ing
them. You can print tf.__version__ (and same for tfp) to check what's being
imported

**Comment by i418c** [comment]
Added both of those steps to the existing gist.  The problems persists.

**Comment by csuter** [comment]
Thanks just wanted to be sure

**Comment by csuter** [comment]
This is beyond my limited keras knowledge. From what I know on the TFP side, it should work. the TensorCoercible mixin just means that the distribution can be passed to TF ops (like tf.add or tf.math.exp) and the distribution will be "cast" to a tf.Tensor by a configurable method (default is sample). Typically, all TF ops call tf.convert_to_tensor on their inputs -- this is the mechanism that "coerces" the distribution to a Tensor. Perhaps keras is not doing this. I am heading out on personal leave shortly and won't have a chance to dig into this. Someone on the keras side might have insight, or maybe @jburnim knows enough to advise.

**Comment by jburnim** [comment]
TFP is not compatible with Keras 3.

To use Keras and TFP together, you must use Keras 2, which can be installed via the `tf-keras` or `tf-keras-nightly` package.  And then import `tf_keras` and use, e.g., `tf_keras.layers.Dense` and `tf_keras.optimizers.Adam` instead of `keras.layers.Dense` and `keras.optimizers.Adam`.  It looks like your example runs with these updates -- https://colab.research.google.com/drive/1EifvJDskVjUOYWzdYXVgHELnTOx75ISe?usp=sharing .

For further info, please see:
 - https://keras.io/keras_3/
 - https://keras.io/getting_started/#tensorflow--keras-2-backwards-compatibility

**Comment by i418c** [comment]
I didn't realize that Keras 3 would be imported under tf.keras or that TFP wouldn't be compatible.  The links were very helpful.  Thanks.
