### ISSUE TITLE
Support batching in tfp.edward2.make_log_joint_fn

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/probability#26]
Currently, the log-probability function returned by Edward2's `make_log_joint_fn` produces a scalar Tensor, summing over any sample and batch dimensions. This prevents sample/batch-wise manipulations of the log-probability.

A naive solution is to simply remove the `tf.reduce_sum`. This assumes that any computations broadcast when the log-probabilities are summed together. That sounds okay, but it produces wrong results. For example,

```python
from tensorflow_probability import edward2 as ed

 def model():
    loc = ed.Normal(loc=0., scale=1., name="loc")
    x = ed.Normal(loc=loc, scale=0.5, sample_shape=5, name="x")
    return x
```

will have a log-joint of

```python
import tensorflow as tf
tfd = tf.contrib.distributions

def log_joint(loc, x):
  log_prob = tfd.Normal(loc=0., scale=1.).log_prob(loc)
  log_prob += tfd.Normal(loc=loc, scale=0.5).log_prob(x)
  return log_prob
```
This element-wise adds the global variable's log-probability to the vector of 5 data point log-probabilities. A final `tf.reduce_sum` will count the global variable's log-probability 5 times instead of 1.

Another solution is to not do any reducing and to have the log-joint return a dict of random variable names and their sample/batch-wise log-probabilities. Another solution is to keep the reduce sum over sample dimensions, but assume broadcasting over batch dimensions.

**Comment by axch** [comment]
What effect do we actually want here?  It seems to me like there is actually a fairly large number of different ways a user might want to batch-evaluate log-joints:
- (Mini-)batches of data broadcasting latents (for SGD optimization or data-annealed inference schemes)
- Batches of latents broadcasting data (for sampling iid chains in batch, or for running particle methods)
- Parallel batches of latents and data (for solving multiple instances of the same model in batch)
- For any set of model variables X, batches of X broadcasting non-X (for particle-within-Gibbs or enumeration-within-Gibbs inference)

It seems we need to design the dimensionality and broadcasting semantics of log_joint carefully in order to support all of these use cases in a clear way.  It feels like this care should be possible, though made more difficult (I think) by tensor dimensions being indexed positionally rather than named semantically.

As a case in point, I can convince myself of two readings of the example:

1. A model with a scalar latent space and an event shape of [5]
2. A model with a scalar latent space and a scalar output space, that was asked to sample a (non-independent) mini-batch of shape [5]

Both readings are actually a little odd: If the event shape is supposed to be [5], where is the Independent bijector that changes Normal's event shape?  If the event shape is supposed to be scalar, why is there a sample_shape argument to Normal in the model at all (since the mini-batch it generates is, in fact, not independent)?

**Comment by davmre** [comment]
A basic criterion that might be helpful to anchor our thinking: if we draw a single joint sample `x, loc ~ model`, then calling `log_joint_fn(x, loc)` on that sample should give back a scalar `log_prob`. This corresponds to the assumption that the event space of the model are program traces, and any particular program trace should be assigned a single, scalar `log_prob` (and for a program with entirely-discrete variables this log prob should in fact be the probability of having sampled that execution trace, with analogous measure-theoretic extension for continuous variables). I think this assumption is pretty fundamental and necessary to any reasonable solution. 

The current behavior (`reduce_sum` over everything) does meet this criterion, and so should any behavior that supports batching. 

Here's a simple proposal: instead of a naive `reduce_sum`, have Edward sum just over the sample and batch dimensions of the underlying RV. That is, we think of each RV in an Edward model as having higher-order "Edward event shape" equal to the shape of the Tensor produced when running the model as a generative process, i.e., the `[sample_shape+batch_shape+event_shape]` of the underlying `Distribution` object. Since each probabilistic event yields a scalar log prob, reducing over the RV's sample and batch shape ensures that each "Edward event" yields a scalar log prob. Any additional dimensions passed in are treated as "Edward batch dimensions" and we don't reduce over them.

We'd implement this as something like 
```python
edward_event_dims = range(-(rv.sample_ndims + rv.batch_ndims), 0)
log_prob += tf.reduce_sum(rv.log_prob(val), axes=edward_event_dims)
```
In practice we'd need to be careful about calculating the ndims in static vs dynamic cases, making sure this does the right thing in edge cases like scalars, etc., but this should just be a matter of careful implementation. For Dustin's example model above, where everything is static, the `log_joint` code might be
```python
def log_joint(loc, x):
  log_prob = tfd.Normal(loc=0., scale=1.).log_prob(loc)
  log_prob += tf.reduce_sum(tfd.Normal(loc=loc, scale=0.5).log_prob(x), axes=-1)
  return log_prob
```
(where `axes=-1` is derived from the fact that `x.sample_shape = [5]` and `x.batch_shape = []`, so the combined sample plus batch shape has one dimension).

This maintains the invariant that `log_prob` is always scalar when we pass in a sample from the model, because at each step we reduce over just those dimensions needed to guarantee that. If we pass in extra batch dimensions for any of the variables, the `log_prob` for that variable will have those dimensions, and the aggregate `log_prob` will have batch dimensions determined by broadcasting. This straightforwardly handles what I expect would be the two most common cases: multiple chains (where all latent variables have a uniform Edward batch shape, and data variables have no Edward batch shape), and data subsampling (where latent variables have no batch shape, and data variables have a uniform Edward batch shape). In the more complex settings Alexey mentioned, the user would have to manually arrange their Edward batch dims to ensure that broadcasting works correctly, but I think that's possible, and consistent with existing semantics of the distributions library. 

(As an aside: this proposal of summing to convert sample and batch dims into higher-order event dims has the flavor of the Independent distribution, but the Independent distribution can only convert batch dims to event dims, whereas here we want to treat both sample *and* batch dims as the event shape of a higher-order distribution. Since in our case the higher-order distribution is directly identified with the Edward model, I think it probably makes sense to implement this behavior directly in Edward, instead of, say, adding a `sample_shape` argument to the Independent distribution and wrapping all Edward RVs with `Independent(sample_shape=rv.sample_shape, reinterpreted_batch_ndims=rv.batch_ndims)`, but that would be an equivalent approach.)

What do y'all think?

**Comment by srvasude** [comment]
Closing this as Edward2's repository has moved to https://github.com/google/edward2
