### ISSUE TITLE
initialize inference in edward2

### ISSUE THREAD

**Issue by kseverso** [tensorflow/probability#314]
In edward, `klqp` had initialization options to set the number of samples for calculating stochastic gradients but I haven't been able to find this parameter is edward2. For instance, how could I change the [PPCA tutorial](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_PCA.ipynb) to specify what would have been `n_samples` in `inference.initialize(n_samples=10)` in edward?

**Comment by davmre** [comment]
Edward2 doesn't have a VI-specific API yet; at the moment it's very much 'whatever you can wire up'. There's no good batteries-included answer to your question, unfortunately.

If you're willing to be a bit adventurous, the most straightforward solution that I know of is to use `tf.map_fn` to evaluate the ELBO multiple times, and `tf.reduce_mean` the result. This works fine in principle, though it's not ideal at an implementation level because it replicates the graph multiple times, so it can become slow (and even run out of memory) when `n_samples` gets large.

In some cases it's possible to avoid these issues using a 'parallel for' loop (`from tensorflow.python.ops.parallel_for import pfor`) to directly parallelize the sampling and log-prob computations of the variational model. We're exploring this internally and it's promising, but there are still some warts (some common ops not supported) and we don't yet have well-tested examples to share.

We'd like to have a better answer to this question soon!

**Comment by kseverso** [comment]
ok, thank you for the quick response!

**Comment by nbro** [comment]
@kseverso Maybe you should keep this issue opened? AFAIK, this problem has not been solved yet.
