### ISSUE TITLE
[TF2.0] Distributions with TF variables

### ISSUE THREAD

**Issue by awav** [tensorflow/probability#333]
Hello everyone,

The TFP's distributions based on TF1.0 could be used with TF variables. Because of the graph building nature of TF1.0, variables are linked with the rest of the operations applied to them within distribution class, so the user can reuse the same distribution instance multiple times. Changing variables passed to the distribution will have an effect on corresponding distribution methods' outputs as well.

In TF2.0 "graph free" world, this nice feature has disappeared. There is no connection between variables and private distribution operations, as everything is computed instantly. Quick look revealed that in simple cases this might be fixed by removing pervasive usage of [`tf.convert_to_tensor` in \_\_init\_\_ method of distributions](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/mvn_tril.py#L193).

TF2.0 behavior:

```python
In [76]: v = tf.Variable(tf.eye(3))
In [77]: m = tf.Variable(tf.ones((3,)))
In [78]: mvn = tfp.distributions.MultivariateNormalTriL(loc=m, scale_tril=v)
In [80]: mvn.mean()
Out[80]: <tf.Tensor: id=1014, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [81]: m.assign(m * 20)
In [82]: m
Out[82]: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([20., 20., 20.], dtype=float32)>

In [83]: mvn.mean()  # EXPECTED TO BE [20., 20., 20.] VECTOR
Out[83]: <tf.Tensor: id=1014, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>
```

That would be nice to keep this feature when TF2.0 released.

Thanks

**Comment by ppham27** [comment]
Not sure if this issue will get much traction. I created a similar issue #212. It looks TF 2.0 shies away from mutable state, so you'll probably have to something like `make_mvn().mean()`.

**Comment by srvasude** [comment]
I am going to close this issue, as I would say this is covered by #448 .

For the issue above as mentioned, this is fixed in TFP. For TFP distributions/bijectors we try to be stateless as possible. That means that we store the parameters passed in to the distribution / bijector at construction time, and then compute the necessary quantities when  a method is invoked (like `.mean()`). We also keep track of all variables in the distribution / bijector (we didn't before which is how this bug surfaced). Feel free to direct more discussion about this to #448.
