### ISSUE TITLE
[Help] Implementing MCMC for Simple Linear Regression

### ISSUE THREAD

**Issue by janithwanni** [tensorflow/probability#339]
Hi there,
I have been interested in implementing a simple linear regression example using tensorflow probability to be added as an example for others to read. I will also be writing a companion article explaining the concepts of probabilistic programming and the uses of it for production.

Instead of using keras layers I decided to build up a prior distribution of weights and biases and then approximate a posterior distribution to give an meaningful insight to the prediction. I first thought of using KLqp divergence but later on found that implementing that and explaining it would not produce an easy introduction to probabilistic programming. Therefore I turned my head towards MCMC and Hamiltonian Monte Carlo as the kernel. 

The code is tried on a colab file linked [here](https://colab.research.google.com/drive/18hLV3fWchzwLDQZzI230iwr9jo0uUx45)

The issue comes from this code segment (executing eagerly)
```
N = X_train.shape[0]
D = 1
#setting sigma2(w) = 1, sigma2(b) = 1, sigma2(y) = 1
X_train = tf.convert_to_tensor(X_train,tf.float32)
y_train = tf.convert_to_tensor(Y_train,tf.float32)
def logistic_regression(X):
  w = tfd.Normal(loc=tf.zeros(D),scale=tf.ones(D),name="w")
  b = tfd.Normal(loc=tf.zeros(1),scale=tf.ones(1),name="b")
  y_loc = tf.add(tf.matmul(X,w.sample(D)),b.sample(D))
  y = tfd.Normal(loc=y_loc,scale=tf.ones([N,D]),name="y")
  return y
qw = tfd.Normal(loc=tf.zeros([D]),scale=tf.ones([D]))
qb = tfd.Normal(loc=tf.zeros([1]),scale=tf.ones([1]))
log_joint = ed.make_log_joint_fn(logistic_regression)
def target_log_prob_fn(w, b):
  """Target log-probability as a function of states."""
  print("target",w,b)
  return log_joint(X_train,w=w,b=b,y=y_train)
hmc_kernel = tfp.mcmc.HamiltonianMonteCarlo(
    target_log_prob_fn=target_log_prob_fn,
    step_size=0.1,
    num_leapfrog_steps=5)
states, kernel_results = tfp.mcmc.sample_chain(
    num_results=1000,
    current_state=[qw,qb],
    kernel=hmc_kernel,
    num_burnin_steps=500)

```
When I run this the sample chain runs for two chains and then breaks with the following error.
```
TypeError: Function result must be a `Tensor` with `float` `dtype`.
```
Any help or pointers to resources are welcome 😄  I'm not exactly sure whether this is something wrong with the way i thought or whether its an issue from tensorflow probability side.

**Comment by axch** [comment]
Hey @janithwanni, sorry for the slow response.

The immediate problem looks like a type error: the `current_state` parameter of `sample_chain` takes `Tensor`s representing points in the sample space, whereas you are passing `Distribution` objects there.  If you meant to initialize randomly from a standard Gaussian, you would spell that as `sample_chain(..., current_state=[qw.sample(), qb.sample()]`.

I see a few other issues you might want to address:

I'm not super-familiar with Edward2, but my impression was that if you wanted the right thing to happen you should use `ed.RandomVariable`s rather than tfp distributions directly: `w = ed.Normal(...)`, etc.  Then I believe Edward takes care of calling `.sample()` for you.

As an alternative, you can just write the joint log density function directly.  Something like (warning: untested code)
```
def target_log_prob_fn(w, b):
  print("target",w,b)
  w_dist = tfd.Normal(loc=tf.zeros(D),scale=tf.ones(D),name="w")
  w_prob = tf.reduce_sum(w_dist.log_prob(w))
  ...
  y_loc = tf.add(tf.matmul(X,w), b)
  y_dist = tfd.Normal(loc=y_loc,scale=tf.ones([N,D]),name="y")
  y_prob = tf.reduce_sum(y_dist.log_prob(y_loc))
  return w_prob + b_prob + y_prob
```

You are also likely to want to tune HMC's parameters for best results.  With have some code for automatically tuning the step size to target an acceptance rate (generally people say to aim for an acceptance rate of 0.5 - 0.9). You'll also want to play with the trajectory length for maximum efficiency (too short gives random-walk behavior and mixes (comparatively) slowly; too long wastes compute running in circles for no benefit).

**Comment by janithwanni** [comment]
Hey @axch 
No problem at all. I tried learning it my own and realized that maybe my knowledge was insufficient as a second year undergraduate studying statistics 😅  
Therefore I took a guided course online on probabilistic programming and I have gained some confidence in this area. Hopefully I can start from where I stopped on this task.
Always excited to be working with Tensorflow! 😄 
I will close the issue now. 
Thank you! 😃
