### ISSUE TITLE
Cumulative Distribution Function for Multivariate Normal distributions

### ISSUE THREAD

**Issue by kyr-pol** [tensorflow/probability#422]
Hi everyone,

I need to use the cdf of a multivariate normal, and after getting a ```NotImplementedError("cdf is not implemented when overriding "
NotImplementedError: cdf is not implemented when overriding event_shape``` error, I realised (also according to this [answer](https://stackoverflow.com/questions/50988462/cdf-of-a-multivariate-normal-in-tensorflow)) that this hasn't been implemented yet. Does that still stand?

If that's the case, I will probably try to implement it myself, at least for my own project (I also found [this](https://stackoverflow.com/questions/39107049/cdf-of-multivariatenormaldiag-in-tensorflow) which can work as a starting point). Should I also make a pull request? If so, I guess it should be a generic method of TransformedDistribution (calling on the pdf of the scalar case) rather than a method of MultivariateNormal?

**Comment by csuter** [comment]
CDF of a general MVN is actually quite a hard problem. I think it's doable in the special case of MVNDiag, though. The MC approach @jvdillon mentions in the SO answer is one way (although gradients through this are hard if not impossible to do usefully).

You can't simply implement it through TransformedDistribution. The problem is that the (inverse) bijector not only transforms the denisty and volume form, but also transforms the region of integration, usually into something rather unwieldy, in the pre-transform domain. In the case of a general MVN, the "(hyper)-quadrant" of integration that you want for the CDF transforms into a sort of convex polytope (but unbounded in some directions). In the case of other bijector-based distributions, it might become something even more complicated (ie, with non-linear boundaries). So then you end up with a simple density (like an isotropic Gaussian) but a terrible region of integration. See, for example, the [wikipedia entry](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Cumulative_distribution_function) and in particular the references on numerical estimates of MVN CDFs.

If you can talk a little more about what you're trying to do, someone might be able to provide better guidance here.

**Comment by kyr-pol** [comment]
Hey, thanks for the quick reply, what I was thinking was the rectangular constraints case. I see your point that with the full covariance, after the transform, the (hyper) rectangle changes shape to a convex polytope. For my application I'd like to get a decent approximation to the cdf (along) with its gradients. So I see two options:

- Stick to the diagonal case, where it should be straightforward, since we only need the one dimensional cdfs, and the gradients are given by the corresponding pdfs. 

- Stick to 2-D where I think you can get the gradients using the pdfs and univariate cdfs and approximate the value with any numerical method (this is more or less what is done in the other SO thread).

**Comment by csuter** [comment]
Cool. IIRC if you use monte carlo to approximate the CDF you can get decent reparameterization gradients w.r.t. the distribution params (loc and scale) but not w.r.t. the limit point of the CDF.

Check out [tfp.monte_carlo.expectation](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/monte_carlo/expectation.py) for a canned MC expectation estimator that should "just work" for getting reparam gradients.

**Comment by kyr-pol** [comment]
Thanks a lot, I'll reopen if I get stuck ;)

**Comment by csuter** [comment]
sounds good. good luck and have fun! :D
