### ISSUE TITLE
Errors in Normal and TruncatedNormal's implementation when variance is 0

### ISSUE THREAD

**Issue by stokhos** [tensorflow/probability#474]
Hi guy:

There is an error with normal distribution when variance is 0.  
```python
RV1 = tfp.edward2.TruncatedNormal(loc=5, scale=0, low=-.2, high=.2)
RV2 = tfp.edward2.TruncatedNormal(loc=2, scale=2, low=-0.2, high=0.2)
RV3 = tfp.edward2.Normal(loc=2, scale=0)


with tf.Session() as sess:
    pprint.pprint(sess.run(RV1.distribution.prob(0.19))) # should be 0. but we got nan
    pprint.pprint(sess.run(RV2.distribution.prob(0.21))) # correct
    pprint.pprint(sess.run(RV3.distribution.prob(0.21))) # should be 0. but we got nan
    pprint.pprint(sess.run(RV3.distribution.prob(2))) # should be 1. but we got nan

    pprint.pprint(sess.run(RV1.distribution.log_prob(0.19))) # should be 0. but we got nan
    pprint.pprint(sess.run(RV2.distribution.log_prob(0.21))) # correct
    pprint.pprint(sess.run(RV3.distribution.log_prob(0.21))) # should be 0. but we got nan
    pprint.pprint(sess.run(RV3.distribution.log_prob(2))) # should be 0. but we got nan
```

This is edge/corner case.  I can help fix this, if you guys want to.

Best
Stokhos

**Comment by davmre** [comment]
Thanks for the report! This is a bit of a weird case; I'd say it's debatably not within the scope of the normal distribution. In particular it's a bit unclear what behavior you'd actually want in this case. For continuity it'd be natural to match the limiting Gaussian density as `scale -> 0`, which is `inf` at the loc and zero elsewhere (the limiting log-density is `inf` at the loc and `-inf` elsewhere) -- but that's different from the behavior you assume. (this gets at the distinction between probability densities vs mass functions). 

Can I ask what your motivation is for using degenerate normal distributions? For many applications, it might make sense to consider `tfd.Deterministic` as an alternative. I believe that does provide the behavior you suggest.

Aside from semantic questions, as a practical matter I think we'd be unlikely to integrate a solution that involved a runtime branch `tf.where` or `tf.cond` in the main `tfd.Normal` log-prob, since that would be a significant speed hit to typical use cases. That said, we're certainly open to discussion and proposals!

**Comment by stokhos** [comment]
Hi Dave,
I'm not sure if this caused the problem in my code. I changed my naive neural network to bayesian neural network. With my naive neural network, I can train a large neural network 4 layers, with more than 200 nodes in each layer, and there were no problem. But with the bayesian neural network, I can't train the same neural network,  because log-likelihood of some observations always give me nans after certain iterations. 

I think this is because when given a truncated normal distribution, at certain iteration, the learned variance accidentally to be 0, or our observation just lies outside the boundary of the truncated normal distribution. Like the above cases. If it were -inf, afterwards iterations would keep updating the parameters of the distribution, until it gives me some reasonable values.  But with nans, afterwards would updating all the parameters to nans.

**Comment by stokhos** [comment]
The following are the outputs from my neural network, and I'd use the outputs as the variance of the normal distribution which generates my observations.
array([[ 119.501724],
       [   7.170488],
       [ 117.495255],
       [ -56.072315],
       [ -55.144547],
       [-102.71122 ],
       [ -19.222078],
       [ 155.67773 ],
       [-172.39136 ],
       [ 140.1985  ],
       [-400.22888 ],
       [  96.34916 ]])
Since the variance should be positive, I map the outputs from neural network to variance through the tf.softplus function. The following are the outputs from softplus function.
 array([[1.19501724e+02],
       [7.17125654e+00],
       [1.17495255e+02],
       [4.44736655e-25],
       [1.12467672e-24],
       [0.00000000e+00],
       [4.48701387e-09],
       [1.55677734e+02],
       [0.00000000e+00],
       [1.40198502e+02],
       [0.00000000e+00],
       [9.63491592e+01]])
SInce there are 0s in the outputs of softplus, we will get nans from Normal(loc, scale=0).
This will happen whenever variance = 0.

**Comment by brianwa84** [comment]
I'd suggest using tf.softplus(output) + 1e-6 or 1e-3, which forces a
minimum variance.

Brian Patton | Software Engineer | bjp@google.com

**Comment by stokhos** [comment]
Yes, this is the workaround I'm using. But I thinking changing nan to 0, would allow us to use a model to learn the upper and lower boundaries of the truncated normal.
