### ISSUE TITLE
Can I predict many univariate related time series ?

### ISSUE THREAD

**Issue by Nathan-Furnal** [tensorflow/probability#506]
Hi,

I'm using TF right now to create quantiles for my forecasts. My dataset is a bunch of related univariate time series. Precisely, monthly sales. 

I'd like to use tensorflow probability and time series to train over the whole dataset and output prob. distributions for many periods for each series and easily access the quantiles (e.g with ``numpy.quantile``.

Is this is a possibility as of version ``0.7.0`` ?

Thanks

**Comment by davmre** [comment]
Sure. It's easiest if you're willing to model all series as independent. Then you can work with a batch of series just by stacking them in a Tensor, and all the STS fitting methods go through essentially as normal:

```python
batch_of_series = get_monthly_sales_data()  #  Tensor of shape [num_series, num_timesteps]
model = tfp.sts.Sum([tfp.sts.LocalLevel(observed_time_series=batch_of_series)], observed_time_series=batch_of_series)  #  Customize to the model of your choice.
variational_loss, posterior_distributions = tfp.sts.build_factored_variational_loss(model, observed_time_series=batch_of_series)
posterior_samples = [q.sample(50) for q in posterior_distributions]
forecast_dists = tfp.sts.forecast(model, batch_of_series, posterior_samples, num_steps_forecast=30)
forecast_samples = forecast_dists.sample(40)

train_op = tf.train.AdamOptimizer(learning_rate=0.1)
with tf.Session() as sess:
  for _ in range(200):  # Fit parameters by optimizing the loss.
    sess.run(train_op)
  # Draw forecasts from the fitted model.
  # These will have shape [sample_size=40, num_series, num_steps_forecast=30].
  forecast_samples_ = sess.run(forecast_samples)

# Compute quantiles. Results have shape [num_series, num_steps_forecast=30].
# Note that you'd probably need more forecast samples if you wanted to to estimate
# quantiles deeper in the tails (0.05, etc).
forecast_quantile_20 = np.quantile(forecast_samples_, 0.2, axis=0)  
forecast_quantile_80 = np.quantile(forecast_samples_, 0.8, axis=0)
```

Note that the forecasts from STS models are mixture distributions of the form `tfd.MixtureSameFamily(posterior_samples, tfd.LinearGaussianStateSpaceModel)`. In principle you could get exact quantiles without sampling by implementing the `.quantile` method on both of those distributions. This would be easy for LGSSMs since the marginals are just Gaussian. MixtureSameFamily would be trickier -- I don't know of an obvious formula for quantiles of a mixture distribution -- but mixture CDFs are easy (and already implemented) so at worst one could numerically invert the CDF. We'd love to have these as contributions!

**Comment by Nathan-Furnal** [comment]
@davmre Thanks a lot for your input! When you say ``sample_size = 40``. Will I take 40 samples for each step or for all step overall?

I'll try to understand the API better and see what I can make of it !

**Comment by davmre** [comment]
Sure thing! The samples are from the forecast distribution, so each sample is a full trajectory over the number of (future) forecast steps you ask for.

If you want the predictive distribution over each time point in your existing data, you can also use `tfp.sts.one_step_predictive` to construct a batch of predictive distributions. Sampling from that will give you `sample_size` samples independently for each step.

**Comment by Nathan-Furnal** [comment]
Interesting stuff, I'll try to get something working then. Can I also add an autoregressive layer for the residuals as shown in the "Regression with probabilistic layers" example ? Thanks

**Comment by davmre** [comment]
Sorry that this slipped through the cracks! IIUC correctly that each row of the matrix represents an independent forecast, then you should get equivalent results from splitting or not splitting, so it'd be up to whatever is faster on your hardware.

I'll close this for now; feel free to reopen if you're still having issues.

Note also that we've updated the STS VI API in recent months to work better with TF2: we now recommend using [`tfp.sts.build_factored_surrogate_posterior`](https://www.tensorflow.org/probability/api_docs/python/tfp/sts/build_factored_surrogate_posterior) and [`tfp.vi.fit_surrogate_posterior`](https://www.tensorflow.org/probability/api_docs/python/tfp/vi/fit_surrogate_posterior) instead of `build_factored_variational_loss`.
