### ISSUE TITLE
forecasting into the future

### ISSUE THREAD

**Issue by cameronse** [tensorflow/probability#525]
Hello,

I am having an issue... when I incorporate external regression my steps to exclude from training data as well as the number of predictions have to match... if i take away the external regression it works perfectly fine. 
Using your variable names I want to exclude 1 from training so num_forecast_steps=1 and I want to predict 36 so num_samples=36. I get an error with this when I add an external regressor. However, if I do num_forecast_steps=36 and num_samples=36 the forecasting works...

Any ideas?

**Comment by davmre** [comment]
Can you post the code that's giving you problems, and/or the specific error?

I'm a bit confused. If you're referring to the names from https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Structural_Time_Series_Modeling_Case_Studies_Atmospheric_CO2_and_Electricity_Demand.ipynb,
there should be no connection between `num_samples` and the number of steps you're predicting --- it only controls how many different forecasts to simulate. Something is likely fishy if you're seeing errors there.

**Comment by cameronse** [comment]
Thank you for getting back to me! 
So I exclude from the training data like this:
demand_training_data= trainingdata [:-num_forecast_steps] ( lets say I exclude 12 months so num forecast steps=12)
When I go to forecast I want to forecast 36 months into the future so I have:
predict_amount=36
tfp.sts.forecast(
    model=demand_model,
    observed_time_series=demand_training_data,
    parameter_samples=q_samples_demand_,
    num_steps_forecast=predict_amount)

If i do this without including the external regressor it runs fine.. I am able to exlude 12 months and predict 36 months. When I add the external regressor component into the model the code will only run if the number of steps excluded from training data >= number of predictions. So in order to predict 36 months into the future I have to exclude 36 months(or more) of training data. If i try using 12 and 36 as in the above example: see the error(s) below:

 Invalid argument: slice index 72 of dimension 1 out of bounds.
2019-08-14 15:33:12.642309: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 72 of dimension 1 out of bounds.
2019-08-14 15:33:12.642309: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 73 of dimension 1 out of bounds.
2019-08-14 15:33:12.642489: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 74 of dimension 1 out of bounds.
2019-08-14 15:33:12.642268: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 72 of di

**Comment by davmre** [comment]
If I'm understanding correctly, it sounds like your issue is that the design matrix in regression components needs to include entries for any steps you plan to forecast, i.e., it should have shape `[num_training_steps + num_forecast_steps, num_features]`. This can be confusing, because that's different from your training `observed_time_series` which has length `num_training_steps`. During training the regression components will only *look* at the first `num_training_steps` rows of the design matrix, because that's all they need to fit the training time series, but you need the extra rows to be present for forecasting.

Does that help? There was some extra discussion around this issue in this thread
https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfprobability/fQJMTK4z8WE/ENhoConrCwAJ,
which might be relevant.

**Comment by cameronse** [comment]
Yes it does! thank you
