### ISSUE TITLE
Advice for MCMC with GPs (not mixing)

### ISSUE THREAD

**Issue by lionfish0** [tensorflow/probability#551]
This is, I'm aware, rather beyond the remit of the TFP issue queue, potentially. 

Simplified to a [sampling-from-a-GP-prior example](https://github.com/lionfish0/experimentation/blob/master/IssueWithMixing.ipynb)*. The key issue is that (after ~burn-in) the observations barely change. This maybe isn't a surprise, they are all highly correlated with neighbours, so the distribution is a very very thin strand in 200 dimensions. However mixing will therefore take a very long time indeed.

Alternatively I could just use lots of separate MCMCs in parallel and combine them. I am suspicious though that this doesn't necessarily sample the distribution correctly - one could imagine a manifold in which the 'outer' edges are more likely to be sampled as that is where the burn-in will end up landing more, if that makes sense.

Anyway, I was wondering if there are better ways of dealing with GPs in TFP, or if there's some other tricks that I should use? (e.g. is teleportation available in TFP, etc). Or maybe I should just accept I'll need to run 100,000s of iterations? Is there a reason why it takes 30s to run 600 iterations (CPU, 10 parallel chains, 200 observations).

Thanks for any advice, sorry if this doesn't quite fit the issue queue (maybe need to post on SO instead).

*My full model has (several) GP priors on the scaling of subsets of observations (somewhat related to [GPRNs](https://arxiv.org/abs/1110.4411)).

**Comment by csuter** [comment]
Hey Mike, thanks for reaching out. I took a look at your example and consulted with @matthewdhoffman. The first thing we tried, to improve mixing, was increasing the number of leapfrog steps dramatically. This allows the chain states to "roll farther downhill" to use the physical metaphor of HMC. Indeed, this improves the mixing, but comes at a terrible computational cost. A significantly better, yet still sub-optimal approach is to use tfp.mcmc.TransformedTransitionKernel to run HMC in a "de-correlated" space of latents. I've adapted your example to demonstrate, in this colab: https://colab.research.google.com/drive/1jeFpgkOsILbln9A4AQ1qUKGbcc6jxh2C#scrollTo=QJtk_Uk5fp93. This solution has a few detriments:
  - I've factored out the kernel from the log joint, which "breaks the spell" a bit as far as model cleanliness goes
  - In order to "precondition" (or, de-correlate) the HMC chains, we have to explicitly compute the cholesky of the kernel matrix, further muddling things
  - with that "fix" in place, our actual log joint computation now contains something like `chol(K)^T @ K^{-1} @ chol(K)`, as well as `-.5 * log |K| + log|chol(K)|` and most likely won't be clever enough to collapse these to `I` and `0`, resp.

Nevertheless, the TransformedTransitionKernel workaround does get things mixing nicely, and perhaps the cancellations may be less of a concern in your non-simplified code (which I'm happy to take a look at, too, if it's helpful).

The final thing my colab does is to wrap the call to `sample_chain` with TensorFlow's `@tf.function` decorator. This is the TF2.0 way of building a computation graph, and will dramatically improve runtime performance. In the colab, I run 1500 steps (500 adaptation+burnin, 1000 samples) of 10 parallel chains with 200 latents in ~25s. Still feels a bit high, but a bit more manageable.

Please do reach out with any further questions! Hope this helps a bit.

**Comment by lionfish0** [comment]
(copied from email)
That was an amazing response! Really helped with the mixing as you said.

I guess this will work until the posterior also becomes highly correlated (relative to the prior), e.g. with lots of observations.
This worked well for my own application (in which the weights 'hyperparameters' are now functions of time have themselves Gaussian process priors). This is related (special case of) the GPRN https://arxiv.org/abs/1110.4411. (they used slice sampling, which I wonder whether it does better than HMC still for highly correlated multidimensional Gaussians).

I'd also developed my own 'hack' which isn't very elegant, and I'm not sure how correct it is, which uses a GP regression model to make predictions at all the observations (these are used to scale the observations depending on which sensor - basically sort of like coregionalisation) - this GP regression model is described by a small number of "latent" observations. This way the hmc has far fewer less correlated points to estimate.

I failed to get the @tf.function thing working. Looks like it has issues with slicing or something... will look at it again.

I'm looking at a variational approximation as I need to extend this eventually to millions of data points (although I'm sure I can [feature] select some of them away).
