### ISSUE TITLE
Branch 0.8.0 doesn't build on py36; unicode error

### ISSUE THREAD

**Issue by jayfurmanek** [tensorflow/probability#571]
Hi. I'm trying to pair a TFP build with Tensorflow 1.15 (rc). I picked the TFP 0.8 branch because it has an RC tagged and has 1.15 as a requirement as listed here:

https://github.com/tensorflow/probability/blob/r0.8/tensorflow_probability/__init__.py#L56

This branch doesn't build for me. I'm using python 3.6 (anaconda).

I'm seeing the same problem as discussed in this issue:
https://github.com/tensorflow/probability/issues/539
and the same fix seems to work -  this commit from master:
https://github.com/tensorflow/probability/commit/2c54a4c04c9f4c07094bba70d185c2233a87ff04

Then on the `bazel-bin/pip_pkg` step, I'm getting a `UnicodeDecodeError: 'ascii' codec can't decode` error. I found if I revert this commit, which adds in the README, it works:
https://github.com/tensorflow/probability/commit/8bf2f950fdf4eab2760f0757f418262c93d64e05

Update:
The first problem is fixed now (thanks!)

**Comment by brianwa84** [comment]
Yes, 0.8 is still intended to parallel the TF 2.0 release, but I've not
been keeping up very well with it. Will probably get to it later today or
sometime next week.

Brian Patton | Software Engineer | bjp@google.com

**Comment by jayfurmanek** [comment]
OK. thanks!  Is there a release that is intended to parallel TF 1.15 then?

I still think the cherry-pick is needed in any case.

**Comment by jayfurmanek** [comment]
I do see this commit though:
https://github.com/tensorflow/probability/commit/bb302dfea351eb065708f18134b0a6f283af89b3

Which is why I was confused a bit.

**Comment by brianwa84** [comment]
I will try to have 0.8.0 compatible with both 1.15 and 2.0, since they are
progressing simultaneously.
Do you have the same issues with the master branch, or other failures with
1.15?

The 'ascii' one is new to me, I don't think we've seen that before and
we're building/uploading a pip pkg every night for tfp-nightly.
https://pypi.org/project/tfp-nightly/
Maybe a specific characteristic of your python/linux install? AFAIK, there
shouldn't be any unicode in that README.md.
Note, we use python3 for our pip upload, so maybe there's an issue with 2.7
(which we probably won't fix, given 12/31 end of support).

Brian Patton | Software Engineer | bjp@google.com

**Comment by jayfurmanek** [comment]
Master seems to be ok for the import problem. I still see the unicode problem though.
I'm using py36, which is why the unicode problem is strange. It's Anacoda py36, but that should'nt make a difference. Pulling the README out does avoid the problem.

>>I will try to have 0.8.0 compatible with both 1.15 and 2.0, since they are progressing  simultaneously.
This is good to know, thanks. I don't see any other issue vs 1.15, but have not really run anything yet since it I thought it was only for 2.0. I can try it a bit more.

**Comment by jayfurmanek** [comment]
Thanks for the cherry-pick!
On the README issue, I still see the unicode problem, but only on python 3.6. It works fine on python 3.7, which is odd.

**Comment by brianwa84** [comment]
Ah, I haven't tried w/ 3.6. We test 3.5 and 3.7 nowadays.

Brian Patton | Software Engineer | bjp@google.com
