### ISSUE TITLE
log_prob returns an error for a transformed Normal distribution

### ISSUE THREAD

**Issue by esdu** [tensorflow/probability#680]
```
tensorflow 2.0.0
tensorflow_probability 0.8.0
```

When we transform a distribution through a bijector, then try to use the `log_prob` of the final distribution, it returns an error

```python
base_dist = tfp.distributions.Normal(loc=0, scale=1) # <-- This doesn't work
# base_dist = tfp.distributions.MultivariateNormalDiag(loc=[0]) # <-- This works

final_dist = tfp.distributions.TransformedDistribution(
    distribution=base_dist,
    bijector=tfp.bijectors.Affine(shift=0.)
)

print(tf.reduce_sum(base_dist.log_prob(base_dist.sample(10))))
# >> tf.Tensor(-16.471008, shape=(), dtype=float32)

print(tf.reduce_sum(final_dist.log_prob(final_dist.sample(10))))
# >> ValueError: event_ndims (0) must be larger than min_event_ndims (1)
```

This happens when the base distribution is a Normal -- however it works when I use a MultivariateNormalDiag.

Please see this Colab to reproduce: https://colab.research.google.com/drive/19ZiYkrpmPDRJXAR5CjfnYJG4fqey6vTU

**Comment by csuter** [comment]
Hey @esdu, this is admittedly a pretty subtle one! `Affine` expects to operate on vector inputs. It'll work if used directly on scalars (due to broadcasting), but behind the scenes, it's telling TransformedDistribution that it expects to map rank-1 things to other rank-1 things, which is causing the error. If you want to use the (scalar) `Normal`, try `AffineScalar` instead. Alternatively, if you use tfp-nightly, you'll find that we've deprecated Affine and AffineScalar in favor of explicitly chaining a `Shift` bijector with one of several `Scale` bijector flavors (which you wouldn't need in this example).

Anyway, switching to AffineScalar in this code snippet should get you moving again 😊

**Comment by esdu** [comment]
Works great. Thank you!
