### ISSUE TITLE
log_prob of Normal is nan when scale is negative

### ISSUE THREAD

**Issue by dwrtz** [tensorflow/probability#721]
From the description of the pdf in the API docs it looks like a negative scale shouldn't cause problems since the pdf uses scale**2.

The MultivariateNormalTriL doesn't have this issue. This inconsistency caught me by surprise. Is this the expected behavior?

Code below shows the issue:

```
import os
import tensorflow_probability as tfp

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
tfd = tfp.distributions


p = tfd.MultivariateNormalTriL(loc=[0,0], scale_tril=[[-1,0],[0,-1]])
q = tfd.Normal(loc=0, scale=-1)

print(p.log_prob([0,0]))
print(q.log_prob(0))
```

This was with tensorflow probability version 0.9.0-dev20200107

**Comment by nbro** [comment]
@dwrtz Which documentation are you exactly referring to? 

The variance of a Gaussian must be non-negative (zero or positive). If you have a Gaussian with zero variance, then the pdf of that Gaussian will be a Dirac function, so the density of any number x (i.e. `d.log(x)`) should probably return `nan`.


Apparently, with TFP, you can create a `Normal` object with negative scales, which, IMHO, shouldn't be allowed, unless there is some use case I am missing. For example, no error is thrown when I execute the following program

```
from tensorflow_probability import distributions

d = distributions.Normal(loc=0, scale=-4)
print(d.stddev())
```

which outputs

```
tf.Tensor(-4.0, shape=(), dtype=float32)
```

Now, consider the following program

```
from tensorflow_probability import distributions as tfd

p = tfd.MultivariateNormalDiag(loc=[0, 0], scale_diag=[[-1, 0], [0, -1]])

print(p.mean())
print(p.stddev())
print(p.prob([0, 0]))
```

produces the following output

```
tf.Tensor([[0. 0.] [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor([[1. 0.] [0. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor([nan nan], shape=(2,), dtype=float32)
```
It seems like the diagonal elements of the diagonal covariance matrix are squared. 

Similarly, the following program

```
from tensorflow_probability import distributions as tfd

p = tfd.MultivariateNormalTriL(loc=[0, 0], scale_tril=[[-1, 0], [0, -1]])
print(p.mean())
print(p.stddev())
```

produces

```
tf.Tensor([0. 0.], shape=(2,), dtype=float32)
tf.Tensor([1. 1.], shape=(2,), dtype=float32)
```

So, yes, the behaviors of the parameters `scale`, `scale_diag` and `scale_tril` or the methods `stddev` of the three classes are not consistent. In fact, it seems like the method `stddev` returns the variance of the distributions. Actually, the covariance matrix should accept a matrix of covariances and variances (and not standard deviations), in order to be consistent with the mathematical definition.

**Comment by csuter** [comment]
A few comments

1. All Distributions accept a `validate_args` constructor argument, which defaults to False. If True, the above negative scale parameters would trigger an assertion. But assertions are potentially costly and we build TFP to be used in high performance applications, so they're disabled by default. We recommend setting `validate_args=True` when you're in an edit/debug cycle, and disabling it once you're ready for your code to run for real.

2. The source of the NaN for the scalar `Normal` in the original post is the `log(scale)` term in the normal log density. when the (scalar) normal is given a negative scale, this log operation returns a NaN.

3. In the MVNDiag case, the corresponding log term is a log *determinant*. The determinant of diag(-1, -1) is 1, so it just happens that it doesn't return a NaN. If you used diag(1, -1) you'd see NaN because the determinant would be negative and the log would barf. Again, though, if you construct that distribution with `validate_args=True` you'll get the error you might expect.

4. stddev, when not explicitly overridden by a distribution class (as is the case for Normal and MVN, IIRC), is computed as the square root of the variance. For these normal distributions, the variance is the square of the scale. So @nbro you're not seeing squares of the scale when you print stddev, you're seeing (positive) square roots of squared (negative) scales, which are then positive.

5. MVN's have a covariance, which is the scale matrix times its transpose. When you ask for the variance, it's just the diagonal of this covariance matrix, and when you ask for stddev, it's the square root of that diagonal.

The meaning of loc and scale in these distributions is definitely chosen to be in accordance with the location-scale terminology you linked to! And I assure you the implementations are consistent with that terminology. If not that would definitely be a bug! But these are some of the most heavily used and tested Distributions in TFP so I'm *extremely* confident they're correct.

Hope this helps you both make sense of what you're seeing and why. More questions welcome!

**Comment by csuter** [comment]
For some context on design choices as you dig deeper into understanding TFP, https://github.com/tensorflow/probability/blob/master/discussion/tfp_distributions_contract.md might be interesting reading. Also the TF Distributions white paper: https://arxiv.org/abs/1711.10604

**Comment by csuter** [comment]
Actually a minor correction:

I MVNTriL will exhibit the behavior I described with the invalid (negative diag) scale, for the reasons I mentioned.

MVNDiag's implementation is actually "closer" in some sense to Normal, and therefore exhibits the same NaN behavior. I'd encourage you to take a look at the code to understand better; it shouldn't be hard to grok what's going on.

At the end of the day though, use `validate_args` and if you're doing an optimization over scales use tf.math.softplus to constrain them to positive reals, or for scale matrices, check out some of our Bijectors for constraining matrices to be positive definite, like `FillScaleTriL` which maps `n * (n + 1) / 2` unconstrained real numbers to an `n x n` lower triangular positive definite matrix.

**Comment by nbro** [comment]
@csuter Maybe there should be a global parameter that can be set (or unset) so that all distributions validate (or not) their parameters? Maybe there's some design pattern for these situations.

**Comment by dwrtz** [comment]
I tried using validate_args=True and it appears that both MultivariateNormalTriL and MultivariateNormalDiag are fine with negative scale matrices. And for both of them log_prob returns a number.

I was able to create what I believe are identical distributions using Normal and MultivariateNormalDiag  but the Normal log_prob is nan

```
p = tfd.MultivariateNormalTriL(loc=[0,0], scale_tril=[[1,0],[0,-1]], validate_args=True)
q = tfd.Normal(loc=0, scale=-1)
r = tfd.MultivariateNormalDiag(loc=[0], scale_diag=[-1], validate_args=True)

print(p.log_prob([0,0]))
print(q.log_prob(0))
print(r.log_prob([0]))
```

**Comment by dwrtz** [comment]
I guess the behavior is consistent in that if validate_args=True doesn't assert then the log_prob will be a number.
