### ISSUE TITLE
No exception and incorrect prob values when using Multinomial for negative cases

### ISSUE THREAD

**Issue by ksachdeva** [tensorflow/probability#756]
Hi,

Consider this setup/example for Multinomial -

Given:
   * Number of trials = 10
   * Cards are draw from deck with replacement. 

Find:
   * The probability of getting 2 spades, 3 diamond, 3 club and 2 hearts.

## Below makes sense  -

```python
p_spade = 13/52
p_diamond = 13/52
p_club = 13/52
p_hearts = 13/52

p = [p_spade, p_diamond, p_club, p_hearts]

card_dist = tfd.Multinomial(total_count=10., probs=p)

card_dist.prob([2,3,3,2])

# Result is - <tf.Tensor: shape=(), dtype=float32, numpy=0.024032602>
```

## Below makes sense to me -

```python
card_dist.prob([2,3])

# Result is  an exception
# InvalidArgumentError: Incompatible shapes: [2] vs. [4] [Op:Mul] name: Multinomial/prob/mul/
```

## Not able to understand this behavior -

```python
card_dist.prob([2])

# Result is <tf.Tensor: shape=(), dtype=float32, numpy=27.685572>
```

Here, I was expecting an exception since the shape of the input is not same as that of probs. Not only I did not get an exception, I got the value of prob to be 27.68. I could have understood 0.0 but why 27.68 ?

## Not able to understand this behavior - 

```python
# note I am using 4 for the second value
# and hence the total is 2+4+3+2=11 instead of 10
card_dist.prob([2, 4, 3, 2])

# Result is <tf.Tensor: shape=(), dtype=float32, numpy=0.0015020376>
```

Here I was expecting the answer to be 0.0 instead of 0.0015020376

##

I have tried the same exercise with scipy and there I get a 0.0 for the situation that is not possible (e..g [2,4,3,2]) and get an exception if I do not respect the shapes of the input

Regards
Kapil

**Comment by axch** [comment]
A couple responses:

1) If you create the multinomial as `tfd.Multinomial(total_count=10., probs=p, validate_args=True)` you will get the exceptions you expect.  We leave the checks off by default because assertions are kind of expensive in TensorFlow (especially graph mode).

2) Broadcasting means that
```
d = tfd.Multinomial(total_count=8., probs=p, validate_args=True)
d.prob([2])
```
actually computes the probability of [2, 2, 2, 2] under that multinomial.

3) Multinomial is currently also returning nonsense results when `validate_args=False` and the total size of the input doesn't agree with the total_count argument.  That's a bug we'll fix shortly.

**Comment by srvasude** [comment]
Going to close this, since `validate_args=True` is the intended way to catch problems like this (we leave checks off since they can be expensive).

I believe we have an open internal issue for a flag to return `0` for `.prob` when you query a distribution off-support.
