### ISSUE TITLE
Incorrect probabilities after transforming a QuantizedDistribution

### ISSUE THREAD

**Issue by RichardWarfield** [tensorflow/probability#761]
The following looks good:
```
dist_spread = tfpd.QuantizedDistribution(
    tfpd.LogNormal(loc=0, scale=0.6931386))

s = 0
for i in np.arange(1, 10, 1):
    print(dist_spread.prob(i).numpy())
    s+= dist_spread.prob(i).numpy()
print("Total:", s)
```
Output:
```
0.5
0.34134775
0.10216706
0.0337364
0.012631168
0.005248601
0.0023717878
0.001147507
0.0005874443
Total: 0.9992377245798707
```

However, when scaling the distribution (such that it is quantized to intervals of 0.5 instead of 1.0), the probabilities sum to 2 instead of 1:

```
dist_spread = tfpd.TransformedDistribution(
  tfpd.QuantizedDistribution(
    tfpd.LogNormal(loc=0, scale=0.6931386)),
  bijector=tfpb.Scale(np.array(0.5, dtype='float32')))

s=0
for i in np.arange(0.5, 5, 0.5):
    print(dist_spread.prob(i).numpy())
    s+= dist_spread.prob(i).numpy()
print("Total:", s)
```
Output:
```
1.0
0.6826955
0.20433412
0.0674728
0.025262335
0.010497202
0.0047435756
0.002295014
0.0011748886
Total: 1.9984754491597414
```

**Comment by axch** [comment]
Good one.  This happens because `Scale` (and all our other bijectors) were written with continuous distributions in mind, where in fact scaling by 0.5 comes with a 2x increase in the probability density (with respect to Lebesgue measure).  Unfortunately, the bijector doesn't know that the distribution it is operating on is actually reporting masses (i.e., densities with respect to the counting measure), so it doesn't know that the correction is incorrect.

I can imagine several different API changes that would fix this.  In the meantime, I guess you could work around it by explicitly canceling out the appropriate log_det_jacobian, which the bijector will happily compute for you upon request.

**Comment by srvasude** [comment]
As mentioned, this is a general problem with our discrete distributions. Bijectors acting on Discrete distributions will unfortunately add their log_det_jacobian.

**Comment by davmre** [comment]
For what it's worth, another workaround in this case is to subclass your own bijector that doesn't do the Jacobian correction.

```python
class DiscreteScale(tfb.Scale):

  def _forward_log_det_jacobian(self, x):
    return 0.

  def _inverse_log_det_jacobian(self, y):
    return 0.
```

**Comment by srvasude** [comment]
This is fixed by https://github.com/tensorflow/probability/commit/4547374bd32c5431c29ca2930ec01961c5e45abd.
