### ISSUE TITLE
Does `Categorical` distribution support mcmc sampling?

### ISSUE THREAD

**Issue by rrkarim** [tensorflow/probability#804]
I'm running the script like this:
```
import numpy as np
import tensorflow.compat.v2 as tf
import tensorflow_probability as tfp
tf.enable_v2_behavior()

tfd = tfp.distributions

dtype = np.float32

target = tfd.Categorical([0.1, 0.9], dtype=dtype)

samples, _ = tfp.mcmc.sample_chain(
  num_results=1000,
  current_state=target.sample(),
  kernel=tfp.mcmc.RandomWalkMetropolis(
     target.log_prob,
     seed=42),
  num_burnin_steps=500,
  parallel_iterations=1)  # For determinism.
```
and it gives me unhandled exception like this: `InvalidArgumentError: Received a label value of 2 which is outside the valid range of [0, 2).  Label values: 2 [Op:SparseSoftmaxCrossEntropyWithLogits]`

Are there some problems with constraint space we are sampling? Doesn't the tfp handles it automatically?

**Comment by csuter** [comment]
You could probably make this work by providing a `new_sample_fn` argument to the RWM kernel and devising some strategy for sampling new proposals (like, maybe an equal-shapeed Categorical with uniform probabilities). By default I think it's using a standard normal for proposals, which is almost never going to sample in the support of that Categorical. Is this a boiled-down example of something more complicated you're trying to achieve? Using RWM to sample from a Categorical seems like overkill :)

A side note: careful with unnamed arguments to Categorical -- as writte, the params you're passing are being interpreted as `logits` (log scale), not `probs`. If you want to treat them as probs, use `Categorical(probs=[.1, .9], ...)`.

**Comment by rrkarim** [comment]
@csuter I was thinking of providing support in `pymc4`. I see for the discrete support delta (still is gaussian perturbation) is actually rounded in `pymc3`. Shouldn't it be support by default in `tfp`?

**Comment by dobos** [comment]
I've come up with this, although I think the log_prob of the joint distribution is computed incorrectly - I have to double check. Here the idea is that the `g` variable is a categorical one and which is sampled N times, the number of items in the mixture. My goal is to compute the marginal probability of every sample being part of each of the mixture components, this is why `g` needs to be sampled. The components in this case have the same distribution but with different `loc` and `scale` (the multivariate normal `m`) and the samples are 2-dimensional vectors. The last variable `obs_m` expresses uncorrelated measurement errors on each of the vector components. My concerns are whether the `Sample` and `Independent` distributions sum up `log_prod` correctly and that this model cannot be sampled by any of the provided MCMC samplers. What happens is that RWM generates floats when perturbing the values of `g` and then cannot update the tensors due to incompatible types. But these type of models are typically sampled with Gibbs sampling anyway by perturbing the categorical variables independently from the (hyper)parameters of the mixture components.

```python
dtype = np.float
N = 10
G = 3
mu = np.array([[0.5, 0.5], [-0.2, -0.5], [0.2, -0.3]], dtype)
sigma = np.array([[[1, 0], [0, 1]], [[1, 0], [0, 1]], [[1, 0], [0, 1]]], dtype)
err = np.array([0.01, 0.01], dtype)

model = tfd.JointDistributionNamed(
    model={
        'gamma':                        
            tfd.Independent(tfd.Deterministic(np.full(G, 0.5, dtype)), reinterpreted_batch_ndims=1),

        'w':        lambda gamma:       
            tfd.Dirichlet(gamma),
        'g':        lambda w:           
            tfd.Sample(tfd.Categorical(probs=w), sample_shape=N),

        'm':        lambda g:   
            tfd.Independent(
                tfd.MultivariateNormalFullCovariance(
                    tf.gather(mu, g),
                    tf.gather(sigma, g)), reinterpreted_batch_ndims=1),

        'obs_m':    lambda m:           
            tfd.Independent(tfd.Normal(m, err, dtype), reinterpreted_batch_ndims=2),
    })
```

**Comment by foabodo** [comment]
László,

I have also encountered this type incompatibility when using RWM to fit a model with a Categorical random variable.

I may have circumvented the problem by switching to a OneHotCategorical RV, for which every sample is a distribution over categories, and then applying tf.math.argmax to identify the most probable category for a given sample.

I say “may have” because I have yet to run MCMC long enough to converge. An alternative formulation of my model that assumes a single hard-coded category converges in ~15k steps. ...not sure what the deal is there.

Franklin
