### ISSUE TITLE
Possible to Mix Joint Distributions?

### ISSUE THREAD

**Issue by zslastman** [tensorflow/probability#828]
I'd like to implement a Tree-Augmented Naive Bayes model in tfp - basically it would be very similiar to:

https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Bayesian_Gaussian_Mixture_Model.ipynb

except that I'd be replacing the multivariate gaussian components of the mixture with JointDistributions, where each Joint distribution would consist of a chain of MultivariateNormals, each of whose mean is a linear function of the previous (so like Naive bayes, only with a single  edge connecting each of the non cluster to a previous one dimensions, and whose edge value value is conditional on the discrete cluster variable).

I'd like this to be fuzzy clustering if possible, so marginalizing over the probability for each cluster.

The canonical tfp way to do that marginalizing is MixtureDistribution, but it seems that MixtureDistribution won't accept JointDistributions as components even if they are identical:

```
locs = tf.constant([.1,.1],shape=[1,2])
scales = tf.constant([.1,.1],shape=[1,2])

comps = [
    tfd.MultivariateNormalDiag(loc=locs,scale_diag=scales),
    tfd.MultivariateNormalDiag(loc=locs,scale_diag=scales)
]

jdist = tfd.JointDistributionSequential([
    tfd.MultivariateNormalDiag(loc=locs,scale_diag=scales)
#    lambda fcs : tfd.MultivariateNormalDiag(loc=locs+fcs,scale_diag=scales)
])
jdists=[jdist,jdist]

#output similiar, except jdists gives a list of TensorShapes
assert comps[0].sample(1).shape  == jdists[0].sample(1)[0].shape

#works
tfp.distributions.Mixture(tfd.Categorical(logits=tf.constant([.1,.1],shape=[1,2]) ),comps)
#fails
tfp.distributions.Mixture(tfd.Categorical(logits=tf.constant([.1,.1],shape=[1,2]) ),jdists)

```

```TypeError: Dimension value must be integer or None or have an __index__ method, got TensorShape([1])
```

Presumably because Joint Distributions have a list of TensorShape objects as their batch shape rather than a single TensorShape object.

I can think of a few ways to work around this - I could probably just make a subclass of JointDistribution that combines the output and has batch_shape and output as a single tensor, or I could write my own Mixture Distribution function that uses logSumExp to get the marginalized probability - but I wanted to make sure there isn't something obvious I'm missing that would make this easy?

**Comment by davmre** [comment]
> where each Joint distribution would consist of a chain of
MultivariateNormals, each of whose mean is a linear function of the previous

Have you thought about whether this could be represented as a
tfd.LinearGaussianStateSpaceModel?
https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/LinearGaussianStateSpaceModel

This would give you efficient exact inference over the Gaussian chain, and
would work with tfd.MixtureSameFamily since it's implemented as a
distribution over vectors rather than a formal JointDistribution.

I think the current implementation of tfd.Mixture predates
JointDistribution, but it might not be very hard to update it to support
mixing over (identically-structured) joint distributions. If you do, we'd
love a PR!

> Presumably because Joint Distributions have a list of TensorShape objects
as their batch shape rather than a single TensorShape object.

I'm guessing the fundamental issue is really the shape of the samples
themselves, but if `.batch_shape` is really the only blocker, you can get
JDs with a single batch shape by using the JointDistribution*AutoBatched
family now in tfp-nightly:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/distributions/joint_distribution_auto_batched.py#L29

> I could probably just make a subclass of JointDistribution that combines
the output and has batch_shape and output as a single tensor

This also sounds like a viable approach. FWIW, we recently updated
TransformedDistribution to support joint distributions:
https://github.com/tensorflow/probability/commit/2cf6fecaf0213ecdfe2d155bf478c83273cefc9d
and expect to have a Split/Concat bijector checked in in the next O(weeks).
Once that happens you'll be able to do this as

```
concatenated_dists = [TransformedDistribution(joint_dist,
Invert(Split(joint_dist.event_shape))) for joint_dist in joint_dists]
mixture_dist = Mixture(cat=..., components=concatenated_dists)
```

Dave

**Comment by zslastman** [comment]
Aha, I think LinearGaussianStateSpaceModel is exactly what I'm looking for, for this iteration of the model anyway. Thanks a million!
