### ISSUE TITLE
Latex formatting for mathematics in documentation

### ISSUE THREAD

**Issue by tirthasheshpatel** [tensorflow/probability#836]
The current "pure text" mathematical equations are quite inconvenient to analyze and understand. It would be really nice to have latex formatted mathematical equations in the documentation. Would it be feasible to change all the equations across the module to latex format?

**Comment by srvasude** [comment]
Hi,
   Unfortunately, I don't think this policy will change. We generally have preferred the more Pythonic text approach due to lack of support in editors and other viewers (for instance in vim it can be quite frustrating seeing and parsing a block of latex): https://github.com/tensorflow/probability/blob/be9f15ee237e92146ee405fed40f9c86f005a3a9/STYLE_GUIDE.md.
