### ISSUE TITLE
Feature Request: Active dimensions for GP kernels

### ISSUE THREAD

**Issue by fonnesbeck** [tensorflow/probability#862]
It does not currently appear to be possible to have kernels apply to specific dimensions of multidimensional inputs. There is a `feature_ndims` that specifies the number of rightmost dimensions to use, but if you wanted to allocate one dimension to one kernel and a second to another, there is no obvious way of doing this. In GPflow (and other packages), there is an `active_dims` argument that can be used to specify the column indicies to be applied to the kernel. This would be useful for building more complex models with GPs in TFP.

**Comment by csuter** [comment]
Thanks, Chris! The current recommended way is to treat slicing as a FeatureTransformed kernel:

```
base_kernel = tfp.math.psd_kernels.ExponentiatedQuadratic(...)
indices = [0, 2, 4]
slicing_kernel = tfp.math.psd_kernels.FeatureTransformed(
    base_kernel,
    transformation_fn=lambda x: tf.gather(x, indicies, axis=-1))
```

**Comment by csuter** [comment]
Note, you can then combine these w/ kernel addition/multiplication...

```
eq_indices = [0, 2, 4]
periodic_indices = [1, 3]
eq_kernel = tfp.math.psd_kernels.FeatureTransformed(
    tfp.math.psd_kernels.ExponentiatedQuadratic(...),
    transformation_fn=lambda x: tf.gather(x, eq_indices, axis=-1))
periodic_kernel = tfp.math.psd_kernels.FeatureTransformed(
    tfp.math.psd_kernels.ExpSinSquared(...),
    transformation_fn=lambda x: tf.gather(x, periodic_indices, axis=-1))

kernel = eq_kernel + periodic_kernel
```

**Comment by csuter** [comment]
Oy, sorry, this is what I get for sharing untested code 😬.

I think we can simply replace `transformation_fn=lambda x, _, _: tf.gather(x, indices, axis=-1)`

The batch_shape non-impl is a real bug. I'm guessing it's left unimplemented because technically the transformation_fn could add batch dimensions to the output, and there's no way for the transformed kernel to know that. A hacky workaround would be to monkey patch a _batch_shape(self) onto FT or the instance itself, which just delegates to the underlying kernel being transformed.

Sorry for the hassle...
