### ISSUE TITLE
MultivariateStudentTLinearOperator log_prob does not match StatsModels

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/probability#977]
I checked the `tfp.distributions.MultivariateStudentTLinearOperator.log_prob` against StatsModel and my own implementation, and the results do not match. Here is a [gist](https://colab.research.google.com/gist/n2cholas/293b1f23e2957ce4440dbe4eb88099ea/multivariate-t-issue.ipynb).

I've tried a few different degrees of freedom, scales, and locations. Is this a bug or am I using `tfp.distributions.MultivariateStudentTLinearOperator` incorrectly? Thanks in advance.

**Comment by SiegeLordEx** [comment]
TFP MVT is not defined in terms of Sigma, but rather in terms of a scale matrix `L` where `Sigma = L L^T`. Typically, L is found via the Cholesky decomposition. E.g. in your example to get the outputs to match up, you could do something like this:

```python
tfp_mvt = tfp.distributions.MultivariateStudentTLinearOperator(
    df, mu, tf.linalg.LinearOperatorLowerTriangular(tf.linalg.cholesky(Sigma))
    ).log_prob(x).numpy()
```

The reason why TFP's MVT is defined this way is because when L is lower triangular, it makes generating samples/computing log prob O(D^2) rather than O(D^3).

**Comment by n2cholas** [comment]
Thanks, that fixed it :D.
