### ISSUE TITLE
ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core'

### ISSUE THREAD

**Issue by yaowang1111** [tensorflow/probability#987]
I have an ImportError when trying to import tfp.
_ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core'_
It might be a problem with tensorflow2.2 or tfp0.10.

See
https://github.com/tensorflow/tensorflow/issues/40584

TFP0.7 doesn't have this problem.

**Comment by syntheticmindAI** [comment]
Use the night build
`pip install tfp-nightly 0.11.0.dev20200708`

**Comment by yaowang1111** [comment]
Thanks！

**Comment by TarasMLAI** [comment]
I'm getting same error. Installing with "conda install -c conda-forge tensorflow-probability" on MacOS M1 silicon. For some reason version 0.8 got installed, however v0.13.0 should be available. Can tensorflow-probability run on M1 silicon at all?

tensorflow-probability    0.8.0                      py_0    conda-forge

**Comment by SDBranka** [comment]
> Use the night build `pip install tfp-nightly 0.11.0.dev20200708`

Has there been an update to this? When I attempted this install I received the message:
 $ pip install tfp-nightly 0.11.0.dev20200708
Collecting tfp-nightly
  Using cached tfp_nightly-0.20.0.dev20230428-py2.py3-none-any.whl (6.9 MB)
ERROR: Could not find a version that satisfies the requirement 0.11.0.dev20200708 (from versions: none)
ERROR: No matching distribution found for 0.11.0.dev20200708

Or have I done something otherwise incorrectly?

**Comment by kaiyuan03** [comment]
@SDBranka 
pip install tfp-nightly==0.11.0.dev20200708 -i https://pypi.org/simple
This works for me.
